import requests
import json
import re
from core.config import LLM_API_URL
from core.config import LLM_MODEL_NAME
from core.config import LLM_TEMPERATURE
from core.utils.chat import ChatSession


def query_llm(
    chat_history: ChatSession,
    command_text: str = None,
    temperature=LLM_TEMPERATURE,
    add_history: bool = True,
    returnJson: bool = True,
) -> dict:
    """
    Generate a JSON command by sending the voice command along with optional chat history
    to the external LLM server.

    Args:
        command_text (str): The latest voice command text.
        chat_history (list, optional): A list of previous messages (each a dict with keys "role" and "content").
            This enables the LLM to consider past context for clarification or follow-up.

    Returns:
        dict: The parsed JSON command generated by the LLM, or an error message.
    """

    if chat_history:
        messages = chat_history
    else:
        # If no chat history, start with an empty list
        messages = ChatSession()
        messages.add_user(command_text)

    if chat_history and command_text:
        # Add the latest command text as a user message
        messages.add_user(command_text)

    # Build the API payload with all conversation context
    payload = {
        "model": LLM_MODEL_NAME,
        "messages": messages.get_messages(),
        "temperature": temperature,
    }

    headers = {
        "Content-Type": "application/json",
    }

    try:
        # Send the request to the external LLM server.
        response = requests.post(LLM_API_URL, headers=headers, json=payload)
        response.raise_for_status()  # Raise for any HTTP errors.

        print(f"🔗 [LLM] Response Status: {response.status_code}")

        if response.status_code != 200:
            print(f"❗ [LLM] Error: {response.text}")
            return {"error": f"LLM request failed with status {response.status_code}"}

        print(f"🔗 [LLM] Response:")
        print(response)

        # Assuming the API response matches a chat-completion format.
        response_data = response.json()
        output_text = response_data["choices"][0]["message"]["content"]
        
        # log raw response data to log file logs/llm_response.log
        with open("logs/llm_response.log", "a", encoding="utf-8") as log_file:
            log_file.write(f"LLM Response:\n{output_text}\n\n")

        # if response has think data, print it and strip it
        if "<think>" in output_text:
            print("💭 Response contains thinking data:", output_text)

        # strip <think> data from response
        output_text = re.sub(r"<think>.*?</think>", "", output_text, flags=re.DOTALL)
        # strip <think> data from response
        output_text = re.sub(r"<think/>", "", output_text, flags=re.DOTALL)
        # strip <think> data from response
        output_text = re.sub(r"<think>", "", output_text, flags=re.DOTALL)

        if returnJson:

            # if text starts with "```json" or "```" then strip it
            if output_text.startswith("```json"):
                output_text = output_text[7:].strip()
            elif output_text.startswith("```"):
                output_text = output_text[3:].strip()

            # if text ends with "```" then strip it
            if output_text.endswith("```"):
                output_text = output_text[:-3].strip()

            # strip any json comments like "//" or "#"
            output_text = re.sub(r"//.*?$|#.*?$", "", output_text, flags=re.MULTILINE)
            # Remove any trailing commas
            output_text = re.sub(r",\s*}", "}", output_text)
            output_text = re.sub(r",\s*]", "]", output_text)

            # Parse the output into a JSON object.
            result = json.loads(output_text)
        else:
            # Return the raw output text if not JSON
            result = output_text

        # Add the LLM response to the chat history
        if add_history:
            if returnJson:
                messages.add_llm_response(result)
            else:
                messages.add_assistant(output_text)

    except Exception as e:
        with open("logs/llm_response.log", "a", encoding="utf-8") as log_file:
            log_file.write(f"LLM Error: Failed to generate JSON comma\n{str(e)}\n")

        result = {"error": f"Failed to generate JSON command: {str(e)}"}

    return result
