import requests
import json
import re
import datetime
from langchain.prompts import PromptTemplate
from core.config import LLM_API_URL
from core.config import LLM_MODEL_NAME
from core.config import LLM_TEMPERATURE

def query_llm(
        command_text: str, 
        chat_history: list = None, 
        temperature = LLM_TEMPERATURE, 
        isTemplate: bool = False, 
        systemPrompt: str = '', 
        replaceSystemPrompt: bool = False,
        returnJson: bool = True
    ) -> dict:
    """
    Generate a JSON command by sending the voice command along with optional chat history
    to the external LLM server.

    Args:
        command_text (str): The latest voice command text.
        chat_history (list, optional): A list of previous messages (each a dict with keys "role" and "content").
            This enables the LLM to consider past context for clarification or follow-up.
    
    Returns:
        dict: The parsed JSON command generated by the LLM, or an error message.
    """

    # Define the prompt template with expected output schema
    if isTemplate:
        final_prompt = command_text
    else:
        prompt_template = """
        Given the following voice command and conversation history, generate a JSON action according to the schema provided below.

        Command: "{command_text}"

        Schema:
        {{
            "action": "<action_name>",
            "module": "<module_name>",
            "parameters": {{"<param_name>": "<param_value>"}},
            "metadata": {{
                "timestamp": "<ISO-8601 timestamp>"
            }}
        }}

        Please ensure the output is a valid JSON object with no extra text. If additional information or confirmation is needed,
        include a field such as "clarification" or "question" instead of the action.
        """
        
        # Prepare the prompt using LangChain's template.
        prompt = PromptTemplate(template=prompt_template, input_variables=["command_text"])
        final_prompt = prompt.format(command_text=command_text)

    current_datetime = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    current_day = datetime.datetime.now().strftime("%A")
    
    # Basic initial system message for context.
    messages = [
        {
            "role": "system", 
            "content": f"""You are an assistant that generates valid JSON output for CRM commands. Provide clarifications if needed. Respond in Czech language. Use correct czech declension of names.
                {systemPrompt}
                Current date and time: {current_datetime} and today is {current_day}
                If any key information is missing, respond with a question to clarify.
            """
        }
    ]

    if replaceSystemPrompt:
        # Replace the system prompt with the new one
        messages[0]['content'] = systemPrompt

    # pretty print the system message
    # print(f"🛠️ [Prompt] system messages: {json.dumps(messages, indent=4)}")

    # Append any existing chat history (e.g. previous messages and clarifications)
    if chat_history:
        messages.extend(chat_history)
    
    # Append the current user prompt
    messages.append({
        "role": "user",
        "content": final_prompt
    })
    
    # Build the API payload with all conversation context
    payload = {
        "model": LLM_MODEL_NAME,  # LM Studio may ignore this
        "messages": messages,
        "temperature": temperature,
    }

    headers = {
        "Content-Type": "application/json",
    }
    
    try:
        # Send the request to the external LLM server.
        response = requests.post(LLM_API_URL, headers=headers, json=payload)
        response.raise_for_status()  # Raise for any HTTP errors.

        # response = response.text

        # Assuming the API response matches a chat-completion format.
        response_data = response.json()
        output_text = response_data["choices"][0]["message"]["content"]

        # if response has think data, print it and strip it
        if "<think>" in output_text:
            print("💭 Response contains thinking data:", output_text)

        # strip <think> data from response
        output_text = re.sub(r"<think>.*?</think>", "", output_text, flags=re.DOTALL)
        # strip <think> data from response
        output_text = re.sub(r"<think/>", "", output_text, flags=re.DOTALL)
        # strip <think> data from response
        output_text = re.sub(r"<think>", "", output_text, flags=re.DOTALL)
        
        if (returnJson):
            # Parse the output into a JSON object.
            result = json.loads(output_text)
        else:
            # Return the raw output text if not JSON
            result = output_text
    except Exception as e:
        result = {"error": f"Failed to generate JSON command: {str(e)}"}
    
    return result
